[package]
name = "auto_pay"
version = "0.1.0"
description = "A minimal template for developing AutoPay with Cairo 1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }
[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."
